name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
      
    - name: SwiftLint
      run: |
        brew install swiftlint
        swiftlint lint --reporter github-actions-logging