name: Build and Test SmartCalc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Resolve Swift Package Dependencies
        run: swift package resolve

      - name: Build Project
        run: swift build -v

      - name: Run Tests
        run: swift test -v

      - name: Lint with SwiftLint
        run: |
          brew install swiftlint
          swiftlint lint --reporter github-actions-logging
        if: success()

      - name: Generate Xcode Project (if needed)
        run: swift package generate-xcodeproj
        if: success()

      - name: Build for iOS
        run: |
          xcodebuild -scheme SmartCalc-Package -sdk iphoneos -configuration Release \
          -destination 'generic/platform=iOS' \
          clean build \
          CODE_SIGNING_ALLOWED=NO
        if: success()

      - name: Archive and Export IPA
        run: |
          mkdir -p build
          xcodebuild -scheme SmartCalc-Package \
          -sdk iphoneos \
          -configuration Release \
          archive \
          -archivePath ./build/SmartCalc.xcarchive \
          CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
          -archivePath ./build/SmartCalc.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist exportOptions.plist \
          CODE_SIGNING_ALLOWED=NO
        if: success()

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SmartCalc-IPA
          path: ./build/SmartCalc.ipa
        if: success()

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: "*.testresult"
        if: always()